Azure/azure-mobile-apps-net-client

e2etest/test/Microsoft.WindowsAzure.MobileServices.Test/FunctionalTests/FromSdkTests/MobileServiceTableTest.cs

Fixes to flaky error message comparisons. 
Note that IDs provided when inserting into an integer ID table are ignored, so no error is raised (removed code block)

Fixes for node SDK

---

e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Functional/PushFunctional.Test.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/Functional/PushFunctional.Test.cs
sdk/src/Microsoft.WindowsAzure.MobileServices.Android/Push/Push.cs
sdk/src/Microsoft.WindowsAzure.MobileServices.iOS/Push/Push.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Microsoft.WindowsAzure.Mobile.Android.Test.csproj
sdk/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Properties/AssemblyInfo.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.Android.Test/TestPlatform/PushTestUtility.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.Android.Test/UnitTests/PushUnit.Test.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.Test/TestPlatform/IPushTestUtility.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.Test/TestPlatform/MissingPushTestUtility.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.WindowsPhone8.Test/TestPlatform/PushTestUtility.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/TestPlatform/PushTestUtility.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/UnitTests/PushUnit.Test.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/Properties/AssemblyInfo.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/TestPlatform/PushTestUtility.cs
sdk/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/UnitTests/PushUnit.Test.cs

Notification Hub requires template body to be a string. Update register templates method to accept template body as string or JSON. Fix for #25

Convert JObject to string for xamarin ios and andriod template parameter's body

---

sdk/src/Microsoft.WindowsAzure.MobileServices/MobileServiceClient.cs

#81 is not a good fix because of the compiler suppression. This fix would be a better one.

Replace #pragma in LogoutAsync method with a better fix

---

e2etest/Android.E2ETest/LoginActivity.cs

Xamarin Android generates names for activities using an MD5 sum as of Android 5.1 [See Xamarin Release Notes] (https://developer.xamarin.com/releases/android/xamarin.android_5/xamarin.android_5.1/#Breaking_Changes). Using this name in our automation scripts is ugly, so I added the name field to the Activity attribute to provide a name that we can rely on in our scripts and that won't have to be updated after code changes.

Adding name attribute to xamarin android login activity

---

e2etest/Android.E2ETest/LoginActivity.cs

Having a package name that starts with a capital letter when referencing the GCM package causes deployment to a device to fail. Fixing that.
http://forums.xamarin.com/discussion/16934/azure-messaging-problem-with-installing-apk

Fixing activity name to not break app deployment

---

src/Microsoft.WindowsAzure.MobileServices.Android/Push/Push.cs
src/Microsoft.WindowsAzure.MobileServices.WindowsStore/Push/Push.cs
src/Microsoft.WindowsAzure.MobileServices.iOS/Push/Push.cs

`MobileServiceClient internalClient = (MobileServiceClient)client;` explicit type conversion could throw InvalidCastException in the runtime, 'as' type conversion will return null in this case.

Use 'as' keyword instead of explicit cast for MobileServiceClient type conversion to avoid potential InvalidCastException

---

e2etest/Net45.E2ETest/UI/TestPage.xaml.cs

This is a bugfix for .NET45 e2etest

Fix a storage container sas token issue for .NET45 e2etest app

---

Microsoft.WindowsAzure.Mobile.Managed_Full_IncludeXamarin.sln

If you run a fresh build of solution Microsoft.WindowsAzure.Mobile.Managed_Full_IncludeXamarin.sln in Visual Studio, you are likely to run into build failure of Win8.E2ETest.csproj because it's dependencies are not built in the correct order.
Micrsoft.WindowsAzure.Mobile.SQLiteStore.csproj is a dependency of Win8.E2ETest.csproj. We need to explicitly state this dependency in .sln file to enforce proper build order in Visual Studio.

Add project build dependencies for Win8.E2ETest to make .sln build success without retries

---

unittest/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Sync/MobileServiceSyncTable.Generic.Test.cs

Unit test PullAsync_Cancels_WhenCancellationTokenIsCancelled() has a race condition of cancelling CancellationToken and invoking PullAsync(). The purpose of the test is to cancel CancellationToken before invoking PullAsync(), however the test is not implemented in the right way. 
The fix is very straightforward, simply calling CancellationToken.Cancel() before calling PullAsync().

Fix a race condition bug in unit test of PullAsync

---

e2etest/UWP.E2ETest/Package.appxmanifest

The package identity for the UWP app was a GUID. Updating it to be more friendly.

[E2ETest][UWP]Updating UWP appxmanifest to have a standard package identity

---

e2etest/E2ETestFramework/Helper/TestConfigHelper.cs
e2etest/UWP.E2ETest/App.xaml.cs
e2etest/UWP.E2ETest/Package.appxmanifest

By adding <uap:Protocol Name="zumoe2e-uwp"> the UWP app can now be launched using the powershell command: start-process zumoe2e-uwp: with the configuration settings passed in as query string parameters. 
Also fixed error with PhoneIdentity change

[E2ETest][UWP]Adding protocol activation to UWP E2ETest

---

src/Microsoft.WindowsAzure.MobileServices.Android/Microsoft.WindowsAzure.Mobile.Ext.Android.csproj
src/Microsoft.WindowsAzure.MobileServices.iOS/Microsoft.WindowsAzure.Mobile.Ext.iOS-Classic.csproj

Disable nuget package reference validation of bcl in Xamarin.Android and Xamarin.iOS project to get rid of warning "All projects referencing Microsoft.WindowsAzure.Mobile.csproj must install nuget package Microsoft.Bcl.Build." in VS.
I learned how to fix it from [this](http://stackoverflow.com/questions/17180268/warning-all-projects-referencing-myproject-csproj-must-install-nuget-package-m) stackoverflow question.

Suppress a BCL nuget warning from Xamarin.Android and Xamarin.iOS project in VS

---

e2etest/WindowsStore.E2ETest/Functional/ClientSDKLoginTests.cs
e2etest/WindowsStore.E2ETest/Win8.E2ETest.csproj
e2etest/WindowsStore.E2ETest/packages.config

[Live SDK](https://github.com/liveservices/LiveSDK) is going to be replaced by [OneDrive SDK](https://github.com/OneDrive/onedrive-sdk-csharp), so it's time to drop Live SDK and pick up OneDrive SDK in e2etest. **OneDrive SDK only supports Windows 8.1, WindowsPhone 8.1 and UWP.** 
This PR fixes the client directed login flow for Microsoft Account using OneDrive SDK. 
PS: OneDrive [wiki](https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/auth.md#microsoft-account-msa-authentication) explains it very well how to use it's authentication API.
@pragnagopa @brettsam Can you take a look?

[e2etest] Use OneDrive SDK for client directed MSA login test instead of Live SDK.

---

e2etest/Android.E2ETest/LoginActivity.cs
e2etest/WindowsPhone8.E2ETest/Functional/LoginTests.cs
e2etest/WindowsStore.E2ETest/Functional/LoginTests.cs
e2etest/iOS.E2ETest/UI/LoginViewController.cs

We add "prompt=consent" in the url parameter on login call to Google as a way to **force** Google showing up the user consent page during web authentication. This is supposed to be a workaround. As App Service Easy-Auth backend fixed the internal issue, we don't need this workaround any more.

[e2etest] Remove client LoginAsync() uri parameter "prompt=consent" of Google account

---

src/Microsoft.WindowsAzure.MobileServices.WindowsStore/Extensions/SingleSignOnExtensions.cs

`LoginAsync(this IMobileServiceClient client, string provider, bool useSingleSignOn, IDictionary<string, string> parameters)` overload in Windows Store extension ignores `IDictionary<string, string> parameters` when `useSingleSignOn` is false. This bug would cause non-single-sign-on login missing url parameters on Windows Store platform. I found this bug from running [Windows Store 8.1 AAD login e2etest](https://github.com/Azure/azure-mobile-apps-net-client/blob/master/e2etest/WindowsStore.E2ETest/Functional/LoginTests.cs#L73). 
@pragnagopa @fabiocav Can you kindly review this?

[Auth] Fix a bug of LoginAsync with parameters with non-single-sign-on

---

e2etest/E2ETestFramework/Framework/TestHarness.cs

The e2etest result file name doesn't contain server platform info. For example, "Net45-master.json" and "Net45-detail.json" for .NET45 managed client. But we run e2etest suites on both .NET backend and Node.js backend. Therefore, it's required to add runtime version to test result.

[e2etest] Add backend info (a.k.a: "RuntimeVersion") to e2etest result reporting

---

e2etest/E2ETestFramework/Framework/MasterTestResult.cs
e2etest/E2ETestFramework/Framework/TestHarness.cs

1. PR #170 modifies the test result json file name without updating the actual file content. This PR fixes this.
2. Adding a new property "backend" to test result json file

[e2etest] Add backend info to test result

---

e2etest/E2ETest/FunctionalTests/CustomAPI/CustomAPIsTests.cs

XML and plaintext parsing are entirely implemented in the custom API itself, the SDK is not being exercised in any meaningful way. Due to failures on Windows phone, this test is being removed.
@dhei @soninaren for info

Removed CustomAPI_SupportsAnyFormat test

---

e2etest/UWP.E2ETest/UWP.E2ETest.csproj
e2etest/WindowsStore.E2ETest/Win8.E2ETest.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.WindowsPhone8.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.WP8.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.WindowsStore.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.Win8.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.Test/Microsoft.WindowsAzure.Mobile.Test.csproj

Moving to latest commit in Xamarin.Auth submodule to address namespace collisions introduced in Xamarin 6.1.0

Update Xamarin.Auth submodule

---

src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/MobileServiceContractResolver.cs
unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Microsoft.WindowsAzure.Mobile.Test.Unit.csproj
unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/MobileServiceContractResolverTests.cs

All the thread safety issues appear to be around the jsonPropertyCache, so I just serialized the writes to the cache and made sure that enumeration was done from a copy. Considering we're already in edge case land I did not go as far as comparing the JsonContract instances returned because there is no convenient equals operation to piggy back onto. But I did inspect the code path and I'm reasonably confident that two racing ResolveContract(..) calls are idempotent.

Resolves #186 - MobileServiceContractResolver is now threadsafe.

---

src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/MobileServiceContractResolver.cs

The same thread can enter a read lock and then make a call to ResolveContract. This can result in an attempt to acquire a write lock, so the read lock for this code path needs to be upgradable.

Fix MobileServiceContractResolver reentrancy issue.

---

.gitignore
src/Microsoft.WindowsAzure.MobileServices/Table/Sync/Queue/Actions/PullAction.cs
src/Microsoft.WindowsAzure.MobileServices/Table/Sync/Queue/OperationQueue.cs
unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/Sync/Queue/Actions/PullActionTests.cs

**Changelog for azure-mobile-apps-net-client**
**********************************************
** Includes code changes for avoiding local store update with pulled records if operation queue already contains same pulled record in it. Added new test method also for the changes done.
** Files modified are :
1. PullAction.cs - Added check for existing operation record same as pulled record to ignore local store update in ProcessAll method (Line - 110)
2.  OperationQueue.cs -  Made GetOperationByItemIdAsync method as virtual so that it can be mocked in the related unit test (Line - 93).
3.  PullActionTests.cs - Added test method DoNotUpdateRecord_IfRecordIsPresentInOperationQueue for code changes done in PushAction.cs (Line 167 - 206).
- Modified existing test method …

Code Change to ignore pulled record if operation queue contains same pulled record in it.

---

e2etest/Android.E2ETest/Android.E2ETest.csproj
src/Microsoft.WindowsAzure.MobileServices/Extensions/MobileServiceSyncTableExtensions.cs
src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncTable.cs

Closes #194 and msazure:933884
Provides the "size of the key" constant and updates the internal code to use the constant.  Sets the constant at 255 (for a larger key size).
Updates the docs in the public interface to match the constant value.

(#194) Updated queryId length to use a constant and set constant to 255

---

e2etest/Android.E2ETest/Android.E2ETest.csproj
src/Microsoft.WindowsAzure.MobileServices/Table/Sync/IMobileServiceSyncTable.Generic.cs
src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncTable.Generic.cs

Updated the IMobileServiceSyncTable.Generic definition to include a purge with force parameter.  Included a concrete example as well.
Closes #56

(#56) Add force purge to generic sync table

---

unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/Sync/MobileServiceSyncTableTests.cs

Need to fix test failure to sign MSIs for SDK build job

Updating query id length for ValidateQueryId_Throws_OnInvalidId test

---

src/Microsoft.Azure.Mobile.Client/Table/Sync/Queue/Operations/MobileServiceTableOperationError.cs

During tests, I noticed that `rawResult` might not be JSON. For example:
`rawResult = "Cannot POST /tables/OfflineReady"`
then, next exception will be thrown:
```C#
Microsoft.WindowsAzure.MobileServices.Sync.MobileServicePushFailedException: Push operation has failed. See the PushResult for details. 
---> Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreException: Failed to read errors from the local store. 
---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
```
In that case, user get parse exception instead of an original error.

Ignore JsonReaderException, because 'rawResult' might not be JSON

---

e2etest/Android.E2ETest/Android.E2ETest.csproj

Xamarin Components are no longer supported in Visual Studio, and should be replaced by NuGet packages.
Fixes #434

Replace xamarin component to nuget reference

---

src/Microsoft.Azure.Mobile.Client/Platforms/android/CurrentPlatform.cs
src/Microsoft.Azure.Mobile.Client/Platforms/ios/CurrentPlatform.cs
src/Microsoft.Azure.Mobile.Client/Platforms/net45/CurrentPlatform.cs
src/Microsoft.Azure.Mobile.Client/Platforms/netstandard14/CurrentPlatform.cs

Fixes #512, #513
`Stream.Close` is unavailable in .NET standard 1.4.
See https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.close
> You do not have to specifically call the `Close` method. Instead, ensure that every `Stream` object is properly disposed.

Fix disposing files

---

e2etest/iOS.E2ETest/Functional/PushFunctional.Test.cs
e2etest/iOS.E2ETest/TestPlatform/PushTestUtility.cs
src/Microsoft.Azure.Mobile.Client/Platforms/ios/Push/Push.cs

This PR is supposed to fix iOS 13 NSData-to-hex conversion.
[#283](https://github.com/Azure/azure-mobile-apps-net-server/issues/283/)
#519 
[AB#71688](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/71688)
[AB#70228](https://dev.azure.com/msmobilecenter/Mobile-Center/_workitems/edit/70228)

Fix NSData convertation for iOS 13

---

azure-pipelines.yml
build.cake
src/Microsoft.Azure.Mobile.Client.SQLiteStore/Microsoft.Azure.Mobile.Client.SQLiteStore.csproj
src/Microsoft.Azure.Mobile.Client/Microsoft.Azure.Mobile.Client.csproj

- Local builds will always be 1.0.0, unless either the `NUGET_VERSION` env var is set or the `nugetVersion` CLI arg is passed.
- CI builds will override the package version using the `BASE_VERSION` variable
- PRs will be `BASE_VERSION-pr.PRNUM.BUILD` or `1.0.0-pr.000.0`
- main branch builds will be `BASE_VERSION-ci.BUILD` or `1.0.0-ci.0`
- Tags will override, so whatever value is used will be the package version (both stable and preview)
If you tag a preview version `4.2.0-preview.1`, then this overrides everything:
- NuGet version == `4.2.0-preview.1`
- Assembly version == `4.2.0`
The `ci` "label" can be changed in the yaml to be anything that is alphanumeric. Things like `preview` or `alpha`, `beta`, `rc` can all be used.

Let CI (or GitHub) control the versions
