sdk/src/Microsoft.WindowsAzure.MobileServices.Android/Properties/AssemblyInfo.cs
sdk/src/Microsoft.WindowsAzure.MobileServices.Net45/Properties/AssemblyInfo.cs
sdk/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/Properties/AssemblyInfo.cs
sdk/src/Microsoft.WindowsAzure.MobileServices.WindowsPhone8.UI/Properties/AssemblyInfo.cs
sdk/src/Microsoft.WindowsAzure.MobileServices.WindowsPhone8/Properties/AssemblyInfo.cs
sdk/src/Microsoft.WindowsAzure.MobileServices.WindowsStore/Properties/AssemblyInfo.cs
sdk/src/Microsoft.WindowsAzure.MobileServices.iOS/Properties/AssemblyInfo.cs
sdk/src/Microsoft.WindowsAzure.MobileServices/Properties/AssemblyInfo.cs

Updating the AssemblyProduct string for the various client sdks

Updating AssemblyProduct information for the managed client sdks

---

component/samples/androidsample/androidsample/androidsample.csproj
component/samples/iOSsample/iOSsample/iOSsample.csproj

Removing some of the changes made in #15 in order to fix a build issue with Android and simplify the build process.

Changes to sample projects to simplify build

---

e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/Functional/PushFunctional.Test.cs

See https://github.com/Azure/azure-mobile-apps-net-client/issues/21

Removed RegisterMultipleAsync

---

e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/PlatformTests/LoginTests.cs

This adds testing Login against Anonymous and Authorized tables for the WinStore app.

Add login test that runs against Anon and Authorized table.

---

component/component.yaml

Adding the ios-unified moniker to the packages to address issues with component submission

---

sdk/src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/MobileServiceSQLiteStore.cs

Serializing access to the transaction scope to prevent issues with SQLite

---

e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/Functional/PushFunctional.Test.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/Functional/PushFunctional.Test.cs

[E2E]Push test fixes

---

e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/App.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.Test/TestPlatform/TestPlatform.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/AppDelegate.cs

Updating TestHarness Platform variables to match pattern in commit 2fa8c8c5422cbe65febaefd98293d4ea1073fb85

Xamarin E2E test change for new reporting technique

---

e2etest/test/Microsoft.WindowsAzure.Mobile.Net45.Test/Microsoft.WindowsAzure.Mobile.Net45.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Microsoft.WindowsAzure.Mobile.Android.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.Test/Microsoft.WindowsAzure.Mobile.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.TestFramework/Microsoft.WindowsAzure.Mobile.TestFramework.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsPhone8.Test/Microsoft.WindowsAzure.Mobile.WP8.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsPhone81.Test/Microsoft.WindowsAzure.Mobile.WP81.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/Microsoft.WindowsAzure.Mobile.Win8.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/Microsoft.WindowsAzure.Mobile.iOS.Test.csproj

Remove `<RestorePackages>true</RestorePackages>`

Remove MSBuild-integrated package restore from e2etest projects

---

e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/App.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Functional/PushFunctional.Test.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/LoginActivity.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Microsoft.WindowsAzure.Mobile.Android.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Properties/AndroidManifest.xml
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Resources/Resource.Designer.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Services/GcmBroadcastReceiver.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Services/GcmService.cs
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/TestPlatform/PushTestUtility.cs
sdk/src/Microsoft.WindowsAzure.MobileServices/Push/PushHttpClient.cs

Adding E2E tests for Xamarin Android Push

---

e2etest/test/Microsoft.WindowsAzure.Mobile.Net45.Test/Microsoft.WindowsAzure.Mobile.Net45.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.Android.Test/Microsoft.WindowsAzure.Mobile.Android.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.Test/Microsoft.WindowsAzure.Mobile.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.TestFramework/Microsoft.WindowsAzure.Mobile.TestFramework.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsPhone8.Test/Microsoft.WindowsAzure.Mobile.WP8.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsPhone81.Test/Microsoft.WindowsAzure.Mobile.WP81.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/Microsoft.WindowsAzure.Mobile.Win8.Test.csproj
e2etest/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/Microsoft.WindowsAzure.Mobile.iOS.Test.csproj
sdk/src/Microsoft.WindowsAzure.MobileServices.iOS/Microsoft.WindowsAzure.Mobile.Ext.iOS.csproj
sdk/test/Microsoft.WindowsAzure.Mobile.Net45.Test/Microsoft.WindowsAzure.Mobile.Net45.Test.csproj
sdk/test/Microsoft.WindowsAzure.MobileServices.SQLiteStore.WindowsStore.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.Win8.Test.csproj
sdk/test/Microsoft.WindowsAzure.MobileServices.Test.Unit/Microsoft.WindowsAzure.Mobile.Test.Unit.csproj
sdk/test/Microsoft.WindowsAzure.MobileServices.Test/Microsoft.WindowsAzure.Mobile.Test.csproj
sdk/test/Microsoft.WindowsAzure.MobileServices.iOS.Test/Microsoft.WindowsAzure.Mobile.iOS.Test.csproj

(Nuget documentation: https://docs.nuget.org/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore)

Migrating MSBuild-Integrated solutions to use Automatic Package Restore for unittest and e2etest

---

README.md

Added reference to SymbolSource in the Useful Resources section of the readme

Adding link to SymbolSource instructions to readme

---

e2etest/Android.E2ETest/Android.E2ETest.csproj
e2etest/Android.E2ETest/LoginActivity.cs

Adding the StorageUrl and StorageKey to the LoginTest activity. Also fixing a configuration issue for Xamarin Android in the SdkRel configuration.

Making changes to xamarin e2etests to accept new params

---

e2etest/WindowsStore.E2ETest/Win8.E2ETest.csproj

Updating the SQLite reference to the latest version in the Windows 8.1 E2E test app

Updating SQLite reference to version 3.11.1.0

---

unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.WindowsStore.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.Win8.Test.csproj

Update SQLite.WinRT81 to 3.11.0 for Win8 unittest project

---

e2etest/Net45.E2ETest/UI/TestPage.xaml.cs

PR #120 fixes the issue but breaks the e2etest automation. This fix should fix the real issue.

Fix a bug in Net45 e2etest preventing it running locally

---

e2etest/UWP.E2ETest/Package.appxmanifest
e2etest/UWP.E2ETest/UWP.E2ETest.csproj

Generated new test cert for uwp e2e project and updated appx reference
Updated reference to SQLLite library with their new naming scheme

[UWP]updating reference to test cert, updating SQLlite reference

---

unittest/Microsoft.WindowsAzure.Mobile.Net45.Test/Microsoft.WindowsAzure.Mobile.Net45.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.Android.Test/Microsoft.WindowsAzure.Mobile.Android.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Android.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.Android.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Net45.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.Net45.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Test.Unit/Microsoft.WindowsAzure.Mobile.SQLiteStore.Test.Unit.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.WindowsPhone8.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.WP8.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.WindowsStore.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.Win8.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.iOS.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.iOS.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Microsoft.WindowsAzure.Mobile.Test.Unit.csproj
unittest/Microsoft.WindowsAzure.MobileServices.Test/Microsoft.WindowsAzure.Mobile.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.WindowsPhone8.Test/Microsoft.WindowsAzure.Mobile.WP8.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.WindowsPhone81.Test/Microsoft.WindowsAzure.Mobile.WP81.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/Microsoft.WindowsAzure.Mobile.Win8.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.iOS.Test/Microsoft.WindowsAzure.Mobile.iOS.Test.csproj

(1) incorrect reference of E2ETest.csproj where should be Microsoft.WindowsAzure.Mobile.Test.csproj
(2) incorrect reference of E2ETestFramework.csproj where should be Microsoft.WindowsAzure.Mobile.TestFramework.csproj

Fix incorrect project reference in unittest projects:

---

src/Microsoft.WindowsAzure.MobileServices.WindowsPhone81/Authentication/AuthenticationBroker.cs
src/Microsoft.WindowsAzure.MobileServices.WindowsStore/Authentication/AuthenticationBroker.cs
unittest/Microsoft.WindowsAzure.MobileServices.WindowsPhone81.Test/App.xaml.cs
unittest/Microsoft.WindowsAzure.MobileServices.WindowsPhone81.Test/Microsoft.WindowsAzure.Mobile.WP81.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/App.xaml.cs
unittest/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/Microsoft.WindowsAzure.Mobile.Win8.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/UnitTests/AuthenticationBroker.Test.cs

Fix Single Sign-On LoginAsync in Windows Store 8 and Windows Phone 8.1 malformated query url issue

---

unittest/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Sync/MobileServiceSyncTable.Generic.Test.cs
unittest/Microsoft.WindowsAzure.MobileServices.WindowsStore.Test/UnitTests/Collections/IncrementalLoadingMobileServiceCollection.Test.cs

Fix unit test PullAsync_Cancels_WhenCancellationTokenIsCancelled race condition issue

---

e2etest/UWP.E2ETest/UWP.E2ETest.csproj

Updating UWP E2E test csproj to have SdkRel configurations

Adding SdkRel configuration to UWP E2E test

---

e2etest/UWP.E2ETest/UI/TestPage.xaml.cs

Added logic to create a completion file at the end of the automated test run

[E2ETest][UWP] Adding completion file logic to UWP E2ETest application

---

CHANGELOG.md
e2etest/Android.E2ETest/Android.E2ETest.csproj
e2etest/E2ETest/E2ETest.csproj
e2etest/E2ETestFramework/E2ETestFramework.csproj
e2etest/Net45.E2ETest/Net45.E2ETest.csproj
e2etest/WindowsPhone8.E2ETest/WP8.E2ETest.csproj
e2etest/WindowsPhone81.E2ETest/WP81.E2ETest.csproj
e2etest/WindowsStore.E2ETest/Win8.E2ETest.csproj

Bump up SDK version to 2.1.0

---

src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/Microsoft.WindowsAzure.Mobile.SQLiteStore.csproj

Add missing IntelliSense Microsoft.WindowsAzure.Mobile.SQLiteStores.xml to SQLiteStore nuget

---

src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/MobileServiceSQLiteStore.cs

Updated the actual path that needs to be specified.

Fix for #244 (file name not specified correctly)

---

e2etest/UWP.E2ETest/UWP.E2ETest.csproj
e2etest/UWP.E2ETest/packages.config
e2etest/UWP.E2ETest/project.json
src/Microsoft.WindowsAzure.MobileServices/Table/Sync/MobileServiceSyncTable.cs

Fixes #215.
Also added Microsoft.Bcl and Microsoft.Bcl.Build to the UWP.E2ETest so it runs properly.  I've checked these files in as well.

(#215) Added formatter to NewGuid.ToString()

---

src/Microsoft.WindowsAzure.MobileServices.SQLiteStore/MobileServiceSQLiteStore.cs
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Test/UnitTests/SQLiteStoreTests.cs

(#196) Expose the ExecuteQueryAsync() method

---

src/Microsoft.Azure.Mobile.Client/Table/Serialization/MobileServiceContractResolver.cs

Fixes #264 - please run unit tests before merging.

Fix for issue264

---

e2etest/Android.E2ETest/Android.E2ETest.csproj
e2etest/E2ETest/E2ETest.csproj
e2etest/E2ETestFramework/E2ETestFramework.csproj
src/Microsoft.Azure.Mobile.Client.SQLiteStore/Microsoft.Azure.Mobile.Client.SQLiteStore.csproj
src/Microsoft.Azure.Mobile.Client/Microsoft.Azure.Mobile.Client.csproj
unittest/Microsoft.WindowsAzure.MobileServices.Android.Test/Microsoft.WindowsAzure.Mobile.Android.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.SQLiteStore.Android.Test/Microsoft.WindowsAzure.Mobile.SQLiteStore.Android.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.Test/Microsoft.WindowsAzure.Mobile.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.TestFramework/Microsoft.WindowsAzure.Mobile.TestFramework.csproj

https://github.com/Azure/azure-mobile-apps-net-client/issues/348

Downgrade Xamarin.Android.Support.CustomTabs to 23.3.0

---

e2etest/E2ETest/OfflineTests.cs

`ClearStore` failed on iOS 11 device with `unable to open database file` error before this change.
This is only e2e tests issue and not related to the SDK itself.

Simplify clear store in offline e2e tests

---

README.md

Add note about git submodules

---

e2etest/iOS.E2ETest/Info.plist

Add support for iPad devices in E2E test application

---

src/Microsoft.Azure.Mobile.Client/Table/Sync/Queue/Actions/PullAction.cs

Cast item carefully in pull action

---

src/Microsoft.Azure.Mobile.Client/Table/Sync/MobileServiceSyncTable.Generic.cs
unittest/Microsoft.WindowsAzure.MobileServices.Test/UnitTests/Table/Sync/MobileServiceSyncTable.Generic.Test.cs

Add parameter validation in MobileServiceSyncTable operations

---

src/Microsoft.Azure.Mobile.Client/Table/Sync/Queue/Actions/PushAction.cs
src/Microsoft.Azure.Mobile.Client/Table/Sync/Queue/Operations/MobileServiceTableOperationError.cs
unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/Sync/Queue/Actions/PushActionTests.cs

Fix NPE when operation item is missing

---

src/Microsoft.Azure.Mobile.Client/Table/Sync/Queue/Actions/PushAction.cs
unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/Sync/Queue/Actions/PushActionTests.cs

Add sync error if item is not found

---

e2etest/E2ETest/E2ETest.csproj
e2etest/E2ETestFramework/E2ETestFramework.csproj
src/Microsoft.Azure.Mobile.Client.SQLiteStore/Microsoft.Azure.Mobile.Client.SQLiteStore.csproj
src/Microsoft.Azure.Mobile.Client/Microsoft.Azure.Mobile.Client.csproj
unittest/Microsoft.WindowsAzure.MobileServices.Test/Microsoft.WindowsAzure.Mobile.Test.csproj
unittest/Microsoft.WindowsAzure.MobileServices.TestFramework/Microsoft.WindowsAzure.Mobile.TestFramework.csproj

Bug in 'MSBuild.Sdk.Extras' v1.0.3 that was fixed in v1.0.5 (see https://github.com/onovotny/MSBuildSdkExtras/issues/12)

Update 'MSBuild.Sdk.Extras' to v1.0.5

---

src/Microsoft.Azure.Mobile.Client/Extensions/ExceptionExtensions.cs
src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs
unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Extensions/ExceptionExtensions.Test.cs

Treat timeout as network error

---

CHANGELOG.md

Note: this changelog doesn't include security fix.

Update changelog for 4.1.0

---

src/Microsoft.Azure.Mobile.Client/Platforms/android/CurrentPlatform.cs
src/Microsoft.Azure.Mobile.Client/Platforms/ios/CurrentPlatform.cs
src/Microsoft.Azure.Mobile.Client/Platforms/net45/CurrentPlatform.cs
src/Microsoft.Azure.Mobile.Client/Platforms/netstandard14/CurrentPlatform.cs

Dispose of files after creating to avoid sharing violation. Fix for issue #512

Dispose files after creating

---

CHANGELOG.md
src/Microsoft.Azure.Mobile.Client/Http/MobileServiceHttpClient.cs

Try to fix UWP regression

---

unittests/MobileClient.Tests/Table/Sync/PullAction.Test.cs

Switched up table.VerifyAll() into table.Verify(something-explicit).

Fixed for the MOQ Test Bug

---

azure-pipelines.yml

Now that everything has been merged, we can remove the WIP items.

Remove the ns2 branch and use a better preview tag

---

azure-pipelines.yml
e2etests/DeviceTests.Android/DeviceTests.Android.csproj
src/Microsoft.Azure.Mobile.Client.SQLiteStore/Microsoft.Azure.Mobile.Client.SQLiteStore.csproj
src/Microsoft.Azure.Mobile.Client/Microsoft.Azure.Mobile.Client.csproj

This will ensure AndroidX support via Essentials
Also cleaned up the references.

Compile Against Android 10 as well :)
